//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:41:45 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www8.garmin.com/xmlschemas/FlightPlan/v1", elementFormDefault = QUALIFIED)
package slash.navigation.fpl.binding;

import static javax.xml.bind.annotation.XmlNsForm.QUALIFIED;