//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.12 at 02:39:09 PM CEST 
//


package slash.navigation.kml.binding22beta;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class NameElement
    extends JAXBElement<String>
{

    protected final static QName NAME = new QName("http://earth.google.com/kml/2.2", "name");

    public NameElement(String value) {
        super(NAME, String.class, null, value);
    }

}
