//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.17 at 01:40:15 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://earth.google.com/kml/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package slash.navigation.kml.binding20;
