//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.07 at 08:39:01 AM CEST 
//


package slash.navigation.geonames.binding;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="geoname">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="geonameId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="countryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fcl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geoname"
})
@XmlRootElement(name = "geonames")
public class Geonames {

    @XmlElement(required = true)
    protected Geonames.Geoname geoname;

    /**
     * Gets the value of the geoname property.
     * 
     * @return
     *     possible object is
     *     {@link Geonames.Geoname }
     *     
     */
    public Geonames.Geoname getGeoname() {
        return geoname;
    }

    /**
     * Sets the value of the geoname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geonames.Geoname }
     *     
     */
    public void setGeoname(Geonames.Geoname value) {
        this.geoname = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="geonameId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="countryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fcl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "lat",
        "lng",
        "geonameId",
        "countryCode",
        "countryName",
        "fcl",
        "fcode",
        "distance"
    })
    public static class Geoname {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected BigDecimal lat;
        @XmlElement(required = true)
        protected BigDecimal lng;
        protected long geonameId;
        @XmlElement(required = true)
        protected String countryCode;
        @XmlElement(required = true)
        protected String countryName;
        @XmlElement(required = true)
        protected String fcl;
        @XmlElement(required = true)
        protected String fcode;
        @XmlElement(required = true)
        protected BigDecimal distance;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the lat property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLat() {
            return lat;
        }

        /**
         * Sets the value of the lat property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLat(BigDecimal value) {
            this.lat = value;
        }

        /**
         * Gets the value of the lng property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLng() {
            return lng;
        }

        /**
         * Sets the value of the lng property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLng(BigDecimal value) {
            this.lng = value;
        }

        /**
         * Gets the value of the geonameId property.
         * 
         */
        public long getGeonameId() {
            return geonameId;
        }

        /**
         * Sets the value of the geonameId property.
         * 
         */
        public void setGeonameId(long value) {
            this.geonameId = value;
        }

        /**
         * Gets the value of the countryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryCode() {
            return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryCode(String value) {
            this.countryCode = value;
        }

        /**
         * Gets the value of the countryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryName() {
            return countryName;
        }

        /**
         * Sets the value of the countryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryName(String value) {
            this.countryName = value;
        }

        /**
         * Gets the value of the fcl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFcl() {
            return fcl;
        }

        /**
         * Sets the value of the fcl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFcl(String value) {
            this.fcl = value;
        }

        /**
         * Gets the value of the fcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFcode() {
            return fcode;
        }

        /**
         * Sets the value of the fcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFcode(String value) {
            this.fcode = value;
        }

        /**
         * Gets the value of the distance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDistance() {
            return distance;
        }

        /**
         * Sets the value of the distance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDistance(BigDecimal value) {
            this.distance = value;
        }

    }

}
