//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 03:39:26 PM CET 
//


package slash.navigation.datasources.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 a bounding box is a north east and a south west position
 *             
 * 
 * <p>Java class for boundingBoxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boundingBoxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="northEast" type="{http://api.routeconverter.com/v1/schemas/datasource-catalog}positionType"/>
 *         &lt;element name="southWest" type="{http://api.routeconverter.com/v1/schemas/datasource-catalog}positionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boundingBoxType", propOrder = {
    "northEast",
    "southWest"
})
public class BoundingBoxType {

    @XmlElement(required = true)
    protected PositionType northEast;
    @XmlElement(required = true)
    protected PositionType southWest;

    /**
     * Gets the value of the northEast property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getNorthEast() {
        return northEast;
    }

    /**
     * Sets the value of the northEast property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setNorthEast(PositionType value) {
        this.northEast = value;
    }

    /**
     * Gets the value of the southWest property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getSouthWest() {
        return southWest;
    }

    /**
     * Sets the value of the southWest property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setSouthWest(PositionType value) {
        this.southWest = value;
    }

}
