//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 03:39:26 PM CET 
//


package slash.navigation.datasources.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 *                 catalog contains edition and datasource definitions.
 *             
 * 
 * <p>Java class for catalogType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="catalogType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="edition" type="{http://api.routeconverter.com/v1/schemas/datasource-catalog}editionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="datasource" type="{http://api.routeconverter.com/v1/schemas/datasource-catalog}datasourceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catalogType", propOrder = {
    "edition",
    "datasource"
})
public class CatalogType {

    protected List<EditionType> edition;
    @XmlElement(required = true)
    protected List<DatasourceType> datasource;

    /**
     * Gets the value of the edition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EditionType }
     * 
     * 
     */
    public List<EditionType> getEdition() {
        if (edition == null) {
            edition = new ArrayList<>();
        }
        return this.edition;
    }

    /**
     * Gets the value of the datasource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datasource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatasource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatasourceType }
     * 
     * 
     */
    public List<DatasourceType> getDatasource() {
        if (datasource == null) {
            datasource = new ArrayList<>();
        }
        return this.datasource;
    }

}
