//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.21 at 07:45:46 PM CET 
//


package slash.navigation.gopal.binding3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="options">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CyclistSpeed" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="Ferries" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="Mode" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="MotorWays" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="PedestrianSpeed" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="TTIMode" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="TollRoad" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="Tunnels" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="VehicleSpeedInPedestrianArea" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="VehicleSpeedMotorway" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="VehicleSpeedNonMotorway" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dest" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="City" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Country" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="House" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="Latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="Longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="StartPos" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="Street" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Zip" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "options",
    "dest"
})
@XmlRootElement(name = "tour")
public class Tour {

    @XmlElement(required = true)
    protected Tour.Options options;
    @XmlElement(required = true)
    protected List<Tour.Dest> dest;

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Tour.Options }
     *     
     */
    public Tour.Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tour.Options }
     *     
     */
    public void setOptions(Tour.Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the dest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tour.Dest }
     * 
     * 
     */
    public List<Tour.Dest> getDest() {
        if (dest == null) {
            dest = new ArrayList<>();
        }
        return this.dest;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="City" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Country" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="House" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="Latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="Longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="StartPos" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="Street" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Zip" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Dest {

        @XmlAttribute(name = "City", required = true)
        protected String city;
        @XmlAttribute(name = "Country", required = true)
        protected short country;
        @XmlAttribute(name = "House")
        protected Short house;
        @XmlAttribute(name = "Latitude", required = true)
        protected long latitude;
        @XmlAttribute(name = "Longitude", required = true)
        protected long longitude;
        @XmlAttribute(name = "StartPos")
        protected Short startPos;
        @XmlAttribute(name = "Street")
        protected String street;
        @XmlAttribute(name = "Zip", required = true)
        protected String zip;

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the country property.
         * 
         */
        public short getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         */
        public void setCountry(short value) {
            this.country = value;
        }

        /**
         * Gets the value of the house property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getHouse() {
            return house;
        }

        /**
         * Sets the value of the house property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setHouse(Short value) {
            this.house = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         */
        public long getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         */
        public void setLatitude(long value) {
            this.latitude = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         */
        public long getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         */
        public void setLongitude(long value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the startPos property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getStartPos() {
            return startPos;
        }

        /**
         * Sets the value of the startPos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setStartPos(Short value) {
            this.startPos = value;
        }

        /**
         * Gets the value of the street property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreet() {
            return street;
        }

        /**
         * Sets the value of the street property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreet(String value) {
            this.street = value;
        }

        /**
         * Gets the value of the zip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZip() {
            return zip;
        }

        /**
         * Sets the value of the zip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZip(String value) {
            this.zip = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CyclistSpeed" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="Ferries" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="Mode" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="MotorWays" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="PedestrianSpeed" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="TTIMode" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="TollRoad" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="Tunnels" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="VehicleSpeedInPedestrianArea" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="VehicleSpeedMotorway" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="VehicleSpeedNonMotorway" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Options {

        @XmlAttribute(name = "CyclistSpeed", required = true)
        protected short cyclistSpeed;
        @XmlAttribute(name = "Ferries", required = true)
        protected short ferries;
        @XmlAttribute(name = "Mode", required = true)
        protected short mode;
        @XmlAttribute(name = "MotorWays", required = true)
        protected short motorWays;
        @XmlAttribute(name = "PedestrianSpeed", required = true)
        protected short pedestrianSpeed;
        @XmlAttribute(name = "TTIMode", required = true)
        protected short ttiMode;
        @XmlAttribute(name = "TollRoad", required = true)
        protected short tollRoad;
        @XmlAttribute(name = "Tunnels", required = true)
        protected short tunnels;
        @XmlAttribute(name = "Type", required = true)
        protected short type;
        @XmlAttribute(name = "VehicleSpeedInPedestrianArea", required = true)
        protected short vehicleSpeedInPedestrianArea;
        @XmlAttribute(name = "VehicleSpeedMotorway", required = true)
        protected short vehicleSpeedMotorway;
        @XmlAttribute(name = "VehicleSpeedNonMotorway", required = true)
        protected short vehicleSpeedNonMotorway;

        /**
         * Gets the value of the cyclistSpeed property.
         * 
         */
        public short getCyclistSpeed() {
            return cyclistSpeed;
        }

        /**
         * Sets the value of the cyclistSpeed property.
         * 
         */
        public void setCyclistSpeed(short value) {
            this.cyclistSpeed = value;
        }

        /**
         * Gets the value of the ferries property.
         * 
         */
        public short getFerries() {
            return ferries;
        }

        /**
         * Sets the value of the ferries property.
         * 
         */
        public void setFerries(short value) {
            this.ferries = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         */
        public short getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         */
        public void setMode(short value) {
            this.mode = value;
        }

        /**
         * Gets the value of the motorWays property.
         * 
         */
        public short getMotorWays() {
            return motorWays;
        }

        /**
         * Sets the value of the motorWays property.
         * 
         */
        public void setMotorWays(short value) {
            this.motorWays = value;
        }

        /**
         * Gets the value of the pedestrianSpeed property.
         * 
         */
        public short getPedestrianSpeed() {
            return pedestrianSpeed;
        }

        /**
         * Sets the value of the pedestrianSpeed property.
         * 
         */
        public void setPedestrianSpeed(short value) {
            this.pedestrianSpeed = value;
        }

        /**
         * Gets the value of the ttiMode property.
         * 
         */
        public short getTTIMode() {
            return ttiMode;
        }

        /**
         * Sets the value of the ttiMode property.
         * 
         */
        public void setTTIMode(short value) {
            this.ttiMode = value;
        }

        /**
         * Gets the value of the tollRoad property.
         * 
         */
        public short getTollRoad() {
            return tollRoad;
        }

        /**
         * Sets the value of the tollRoad property.
         * 
         */
        public void setTollRoad(short value) {
            this.tollRoad = value;
        }

        /**
         * Gets the value of the tunnels property.
         * 
         */
        public short getTunnels() {
            return tunnels;
        }

        /**
         * Sets the value of the tunnels property.
         * 
         */
        public void setTunnels(short value) {
            this.tunnels = value;
        }

        /**
         * Gets the value of the type property.
         * 
         */
        public short getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         */
        public void setType(short value) {
            this.type = value;
        }

        /**
         * Gets the value of the vehicleSpeedInPedestrianArea property.
         * 
         */
        public short getVehicleSpeedInPedestrianArea() {
            return vehicleSpeedInPedestrianArea;
        }

        /**
         * Sets the value of the vehicleSpeedInPedestrianArea property.
         * 
         */
        public void setVehicleSpeedInPedestrianArea(short value) {
            this.vehicleSpeedInPedestrianArea = value;
        }

        /**
         * Gets the value of the vehicleSpeedMotorway property.
         * 
         */
        public short getVehicleSpeedMotorway() {
            return vehicleSpeedMotorway;
        }

        /**
         * Sets the value of the vehicleSpeedMotorway property.
         * 
         */
        public void setVehicleSpeedMotorway(short value) {
            this.vehicleSpeedMotorway = value;
        }

        /**
         * Gets the value of the vehicleSpeedNonMotorway property.
         * 
         */
        public short getVehicleSpeedNonMotorway() {
            return vehicleSpeedNonMotorway;
        }

        /**
         * Sets the value of the vehicleSpeedNonMotorway property.
         * 
         */
        public void setVehicleSpeedNonMotorway(short value) {
            this.vehicleSpeedNonMotorway = value;
        }

    }

}
