Title,Code,Country,Latitude,Longitude,Elevation,Style,Direction,Length,Frequency,Description
"bei D 22885 Barsbüttel/Stemwarde",bei D 22885 Barsbüttel/Stemwarde,,5334.318N,01014.646E,5.0m,1,,,,""
"bei D 22946 Großensee/Schwarzekate",bei D 22946 Großensee/Schwarzekate,,5336.816N,01019.719E,134.0m,1,,,,""
"bei D 22952 Lütjensee/Bollmoor",bei D 22952 Lütjensee/Bollmoor,,5338.091S,01022.937W,-18.0m,1,,,,""
"bei D 22956 Grönwohld",bei D 22956 Grönwohld,,5338.504N,01024.498E,5.0m,1,,,,"Geocache"
"bei D 22959 Linau",bei D 22959 Linau,,5338.611N,01027.808E,134.0m,1,,,,"Geocache"
