//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.13 at 10:12:26 PM MESZ 
//


package slash.navigation.kml.binding22gx;

import slash.navigation.kml.binding22.TimeSpanType;
import slash.navigation.kml.binding22.TimeStampType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the slash.navigation.kml.binding22gx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MultiTrack_QNAME = new QName("http://www.google.com/kml/ext/2.2", "MultiTrack");
    private final static QName _AltitudeMode_QNAME = new QName("http://www.google.com/kml/ext/2.2", "altitudeMode");
    private final static QName _LatLonQuad_QNAME = new QName("http://www.google.com/kml/ext/2.2", "LatLonQuad");
    private final static QName _AnimatedUpdate_QNAME = new QName("http://www.google.com/kml/ext/2.2", "AnimatedUpdate");
    private final static QName _Coord_QNAME = new QName("http://www.google.com/kml/ext/2.2", "coord");
    private final static QName _TimeSpan_QNAME = new QName("http://www.google.com/kml/ext/2.2", "TimeSpan");
    private final static QName _Track_QNAME = new QName("http://www.google.com/kml/ext/2.2", "Track");
    private final static QName _H_QNAME = new QName("http://www.google.com/kml/ext/2.2", "h");
    private final static QName _Y_QNAME = new QName("http://www.google.com/kml/ext/2.2", "y");
    private final static QName _X_QNAME = new QName("http://www.google.com/kml/ext/2.2", "x");
    private final static QName _Tour_QNAME = new QName("http://www.google.com/kml/ext/2.2", "Tour");
    private final static QName _W_QNAME = new QName("http://www.google.com/kml/ext/2.2", "w");
    private final static QName _TimeStamp_QNAME = new QName("http://www.google.com/kml/ext/2.2", "TimeStamp");
    private final static QName _SimpleArrayData_QNAME = new QName("http://www.google.com/kml/ext/2.2", "SimpleArrayData");
    private final static QName _FlyToMode_QNAME = new QName("http://www.google.com/kml/ext/2.2", "flyToMode");
    private final static QName _Playlist_QNAME = new QName("http://www.google.com/kml/ext/2.2", "Playlist");
    private final static QName _SimpleArrayDataExtension_QNAME = new QName("http://www.google.com/kml/ext/2.2", "SimpleArrayDataExtension");
    private final static QName _Interpolate_QNAME = new QName("http://www.google.com/kml/ext/2.2", "interpolate");
    private final static QName _BalloonVisibility_QNAME = new QName("http://www.google.com/kml/ext/2.2", "balloonVisibility");
    private final static QName _AbstractTrackSimpleExtensionGroup_QNAME = new QName("http://www.google.com/kml/ext/2.2", "AbstractTrackSimpleExtensionGroup");
    private final static QName _PlayMode_QNAME = new QName("http://www.google.com/kml/ext/2.2", "playMode");
    private final static QName _TourControl_QNAME = new QName("http://www.google.com/kml/ext/2.2", "TourControl");
    private final static QName _SimpleArrayField_QNAME = new QName("http://www.google.com/kml/ext/2.2", "SimpleArrayField");
    private final static QName _SimpleArrayFieldExtension_QNAME = new QName("http://www.google.com/kml/ext/2.2", "SimpleArrayFieldExtension");
    private final static QName _Rank_QNAME = new QName("http://www.google.com/kml/ext/2.2", "rank");
    private final static QName _AbstractTourPrimitive_QNAME = new QName("http://www.google.com/kml/ext/2.2", "AbstractTourPrimitive");
    private final static QName _AbstractTourPrimitiveGroup_QNAME = new QName("http://www.google.com/kml/ext/2.2", "AbstractTourPrimitiveGroup");
    private final static QName _Wait_QNAME = new QName("http://www.google.com/kml/ext/2.2", "Wait");
    private final static QName _Value_QNAME = new QName("http://www.google.com/kml/ext/2.2", "value");
    private final static QName _SoundCue_QNAME = new QName("http://www.google.com/kml/ext/2.2", "SoundCue");
    private final static QName _Angles_QNAME = new QName("http://www.google.com/kml/ext/2.2", "angles");
    private final static QName _FlyTo_QNAME = new QName("http://www.google.com/kml/ext/2.2", "FlyTo");
    private final static QName _Duration_QNAME = new QName("http://www.google.com/kml/ext/2.2", "duration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: slash.navigation.kml.binding22gx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleArrayDataType }
     * 
     */
    public SimpleArrayDataType createSimpleArrayDataType() {
        return new SimpleArrayDataType();
    }

    /**
     * Create an instance of {@link SimpleArrayFieldType }
     * 
     */
    public SimpleArrayFieldType createSimpleArrayFieldType() {
        return new SimpleArrayFieldType();
    }

    /**
     * Create an instance of {@link SoundCueType }
     * 
     */
    public SoundCueType createSoundCueType() {
        return new SoundCueType();
    }

    /**
     * Create an instance of {@link LatLonQuadType }
     * 
     */
    public LatLonQuadType createLatLonQuadType() {
        return new LatLonQuadType();
    }

    /**
     * Create an instance of {@link AbstractTourPrimitiveType }
     * 
     */
    public AbstractTourPrimitiveType createAbstractTourPrimitiveType() {
        return new AbstractTourPrimitiveType();
    }

    /**
     * Create an instance of {@link TrackType }
     * 
     */
    public TrackType createTrackType() {
        return new TrackType();
    }

    /**
     * Create an instance of {@link PlaylistType }
     * 
     */
    public PlaylistType createPlaylistType() {
        return new PlaylistType();
    }

    /**
     * Create an instance of {@link TourControlType }
     * 
     */
    public TourControlType createTourControlType() {
        return new TourControlType();
    }

    /**
     * Create an instance of {@link WaitType }
     * 
     */
    public WaitType createWaitType() {
        return new WaitType();
    }

    /**
     * Create an instance of {@link FlyToType }
     * 
     */
    public FlyToType createFlyToType() {
        return new FlyToType();
    }

    /**
     * Create an instance of {@link MultiTrackType }
     * 
     */
    public MultiTrackType createMultiTrackType() {
        return new MultiTrackType();
    }

    /**
     * Create an instance of {@link AnimatedUpdateType }
     * 
     */
    public AnimatedUpdateType createAnimatedUpdateType() {
        return new AnimatedUpdateType();
    }

    /**
     * Create an instance of {@link TourType }
     * 
     */
    public TourType createTourType() {
        return new TourType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiTrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "MultiTrack", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractGeometryGroup")
    public JAXBElement<MultiTrackType> createMultiTrack(MultiTrackType value) {
        return new JAXBElement<>(_MultiTrack_QNAME, MultiTrackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AltitudeModeEnumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "altitudeMode", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "altitudeModeGroup")
    public JAXBElement<AltitudeModeEnumType> createAltitudeMode(AltitudeModeEnumType value) {
        return new JAXBElement<>(_AltitudeMode_QNAME, AltitudeModeEnumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LatLonQuadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "LatLonQuad", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "GroundOverlayObjectExtensionGroup")
    public JAXBElement<LatLonQuadType> createLatLonQuad(LatLonQuadType value) {
        return new JAXBElement<>(_LatLonQuad_QNAME, LatLonQuadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnimatedUpdateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "AnimatedUpdate", substitutionHeadNamespace = "http://www.google.com/kml/ext/2.2", substitutionHeadName = "AbstractTourPrimitiveGroup")
    public JAXBElement<AnimatedUpdateType> createAnimatedUpdate(AnimatedUpdateType value) {
        return new JAXBElement<>(_AnimatedUpdate_QNAME, AnimatedUpdateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "coord")
    public JAXBElement<String> createCoord(String value) {
        return new JAXBElement<>(_Coord_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeSpanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "TimeSpan", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractViewObjectExtensionGroup")
    public JAXBElement<TimeSpanType> createTimeSpan(TimeSpanType value) {
        return new JAXBElement<>(_TimeSpan_QNAME, TimeSpanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "Track", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractGeometryGroup")
    public JAXBElement<TrackType> createTrack(TrackType value) {
        return new JAXBElement<>(_Track_QNAME, TrackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "h", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "BasicLinkSimpleExtensionGroup")
    public JAXBElement<BigInteger> createH(BigInteger value) {
        return new JAXBElement<>(_H_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "y", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "BasicLinkSimpleExtensionGroup")
    public JAXBElement<BigInteger> createY(BigInteger value) {
        return new JAXBElement<>(_Y_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "x", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "BasicLinkSimpleExtensionGroup")
    public JAXBElement<BigInteger> createX(BigInteger value) {
        return new JAXBElement<>(_X_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TourType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "Tour", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractFeatureGroup")
    public JAXBElement<TourType> createTour(TourType value) {
        return new JAXBElement<>(_Tour_QNAME, TourType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "w", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "BasicLinkSimpleExtensionGroup")
    public JAXBElement<BigInteger> createW(BigInteger value) {
        return new JAXBElement<>(_W_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "TimeStamp", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractViewObjectExtensionGroup")
    public JAXBElement<TimeStampType> createTimeStamp(TimeStampType value) {
        return new JAXBElement<>(_TimeStamp_QNAME, TimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleArrayDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "SimpleArrayData", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "SchemaDataExtension")
    public JAXBElement<SimpleArrayDataType> createSimpleArrayData(SimpleArrayDataType value) {
        return new JAXBElement<>(_SimpleArrayData_QNAME, SimpleArrayDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlyToModeEnumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "flyToMode", defaultValue = "bounce")
    public JAXBElement<FlyToModeEnumType> createFlyToMode(FlyToModeEnumType value) {
        return new JAXBElement<>(_FlyToMode_QNAME, FlyToModeEnumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaylistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "Playlist", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractObjectGroup")
    public JAXBElement<PlaylistType> createPlaylist(PlaylistType value) {
        return new JAXBElement<>(_Playlist_QNAME, PlaylistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "SimpleArrayDataExtension")
    public JAXBElement<Object> createSimpleArrayDataExtension(Object value) {
        return new JAXBElement<>(_SimpleArrayDataExtension_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "interpolate", defaultValue = "false")
    public JAXBElement<Boolean> createInterpolate(Boolean value) {
        return new JAXBElement<>(_Interpolate_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "balloonVisibility", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractFeatureSimpleExtensionGroup", defaultValue = "true")
    public JAXBElement<Boolean> createBalloonVisibility(Boolean value) {
        return new JAXBElement<>(_BalloonVisibility_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "AbstractTrackSimpleExtensionGroup")
    public JAXBElement<Object> createAbstractTrackSimpleExtensionGroup(Object value) {
        return new JAXBElement<>(_AbstractTrackSimpleExtensionGroup_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayModeEnumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "playMode", defaultValue = "pause")
    public JAXBElement<PlayModeEnumType> createPlayMode(PlayModeEnumType value) {
        return new JAXBElement<>(_PlayMode_QNAME, PlayModeEnumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TourControlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "TourControl", substitutionHeadNamespace = "http://www.google.com/kml/ext/2.2", substitutionHeadName = "AbstractTourPrimitiveGroup")
    public JAXBElement<TourControlType> createTourControl(TourControlType value) {
        return new JAXBElement<>(_TourControl_QNAME, TourControlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleArrayFieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "SimpleArrayField", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "SchemaExtension")
    public JAXBElement<SimpleArrayFieldType> createSimpleArrayField(SimpleArrayFieldType value) {
        return new JAXBElement<>(_SimpleArrayField_QNAME, SimpleArrayFieldType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "SimpleArrayFieldExtension")
    public JAXBElement<Object> createSimpleArrayFieldExtension(Object value) {
        return new JAXBElement<>(_SimpleArrayFieldExtension_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "rank", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractFeatureSimpleExtensionGroup", defaultValue = "0.0")
    public JAXBElement<Double> createRank(Double value) {
        return new JAXBElement<>(_Rank_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractTourPrimitiveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "AbstractTourPrimitive")
    public JAXBElement<AbstractTourPrimitiveType> createAbstractTourPrimitive(AbstractTourPrimitiveType value) {
        return new JAXBElement<>(_AbstractTourPrimitive_QNAME, AbstractTourPrimitiveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractTourPrimitiveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "AbstractTourPrimitiveGroup", substitutionHeadNamespace = "http://www.opengis.net/kml/2.2", substitutionHeadName = "AbstractObjectGroup")
    public JAXBElement<AbstractTourPrimitiveType> createAbstractTourPrimitiveGroup(AbstractTourPrimitiveType value) {
        return new JAXBElement<>(_AbstractTourPrimitiveGroup_QNAME, AbstractTourPrimitiveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WaitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "Wait", substitutionHeadNamespace = "http://www.google.com/kml/ext/2.2", substitutionHeadName = "AbstractTourPrimitiveGroup")
    public JAXBElement<WaitType> createWait(WaitType value) {
        return new JAXBElement<>(_Wait_QNAME, WaitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoundCueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "SoundCue", substitutionHeadNamespace = "http://www.google.com/kml/ext/2.2", substitutionHeadName = "AbstractTourPrimitiveGroup")
    public JAXBElement<SoundCueType> createSoundCue(SoundCueType value) {
        return new JAXBElement<>(_SoundCue_QNAME, SoundCueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "angles")
    public JAXBElement<String> createAngles(String value) {
        return new JAXBElement<>(_Angles_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlyToType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "FlyTo", substitutionHeadNamespace = "http://www.google.com/kml/ext/2.2", substitutionHeadName = "AbstractTourPrimitiveGroup")
    public JAXBElement<FlyToType> createFlyTo(FlyToType value) {
        return new JAXBElement<>(_FlyTo_QNAME, FlyToType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.google.com/kml/ext/2.2", name = "duration", defaultValue = "0.0")
    public JAXBElement<Double> createDuration(Double value) {
        return new JAXBElement<>(_Duration_QNAME, Double.class, null, value);
    }

}
