//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.16-hudson-jaxb-ri-2.1-pushtomaven-250--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 04:01:32 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = GARMIN_TRIP_EXTENSIONS_1_NAMESPACE_URI, elementFormDefault = QUALIFIED, xmlns = {
        @XmlNs(prefix = "trp", namespaceURI = GARMIN_TRIP_EXTENSIONS_1_NAMESPACE_URI) })
package slash.navigation.gpx.trip1;

import javax.xml.bind.annotation.XmlNs;

import static javax.xml.bind.annotation.XmlNsForm.QUALIFIED;
import static slash.navigation.gpx.GpxUtil.GARMIN_TRACKPOINT_EXTENSIONS_2_NAMESPACE_URI;
import static slash.navigation.gpx.GpxUtil.GARMIN_TRIP_EXTENSIONS_1_NAMESPACE_URI;