//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.29 at 02:46:22 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.routeconverter.com/v1/schemas/mapserver-catalog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package slash.navigation.maps.tileserver.bindingmap;
