//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.25 at 04:56:33 PM CET 
//


package slash.navigation.googlemaps.elevation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the slash.navigation.googlemaps.elevation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: slash.navigation.googlemaps.elevation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ElevationResponse }
     * 
     */
    public ElevationResponse createElevationResponse() {
        return new ElevationResponse();
    }

    /**
     * Create an instance of {@link ElevationResponse.Result.Location }
     * 
     */
    public ElevationResponse.Result.Location createElevationResponseResultLocation() {
        return new ElevationResponse.Result.Location();
    }

    /**
     * Create an instance of {@link ElevationResponse.Result }
     * 
     */
    public ElevationResponse.Result createElevationResponseResult() {
        return new ElevationResponse.Result();
    }

}
